### ISSUE TITLE
isotp-c integration (updates)

### ISSUE THREAD

**Issue by SimonCahill** [driftregion/iso14229#26]
Hi there!

A while ago you integrated my fork of the isotp-c library in this project.
I just wanted to inform you that several updates have been published since, and I thought it would be good to inform you.

The latest version is [v1.1.1](https://github.com/SimonCahill/isotp-c/releases/tag/v1.1.1).

**Comment by driftregion** [comment]
Thanks Simon for this notification. I appreciate your work.
I'm still running a fork with a modified  `isotp_user_send_can` that accepts an additional `void *` so that multiple CAN interfaces may be used by one binary. Is this something you'd consider upstreaming?

**Comment by SimonCahill** [comment]
Sounds like a good feature!

To maintain backward-compat. could you add this as an option in the Makefile and CMakeLists?
That way this feature could be enabled at compile-time.

Shoot me a PR and I'll see it gets merged :)

**Comment by driftregion** [comment]
Sounds good. Next time I touch isotp-c I'll send a PR. It might be a while though. The library never has any problems. ;)

**Comment by SimonCahill** [comment]
No worries, I'm looking forward to the contribution!
Take your time, it's no rush

**Comment by driftregion** [comment]
Hi Simon, I took a stab at this here:

https://github.com/SimonCahill/isotp-c/pull/36
