### ISSUE TITLE
"Response Pending" (NRC 0x78)

### ISSUE THREAD

**Issue by guru0808** [driftregion/iso14229#33]
Hi,
I wish to implement UDS using this repo. It seems fine work to me. However i wish to use "Response Pending" (NRC 0x78) and would like to know if you have implemented delayed response sending.

**Comment by driftregion** [comment]
Yes, here are the tests for NRC 0x78:
https://github.com/driftregion/iso14229/blob/main/test/test_client_0x31_RCRRP.c
https://github.com/driftregion/iso14229/blob/main/test/test_server_0x31_RCRRP.c

**Comment by guru0808** [comment]
Thanks.
Both releases have following cases
`
#if UDS_SYS == **UDS_SYS_WIN32**

#include <BaseTsd.h>
typedef SSIZE_T ssize_t;

#endif
`
However, you have used #define UDS_SYS **UDS_SYS_WINDOWS**
