### ISSUE TITLE
Build Err

### ISSUE THREAD

**Issue by dhje0ng** [driftregion/iso14229#49]
**Describe the bug**

After cloning the iso14229 git repository, I noticed that the make command creates iso14229.c, iso14229.h in the release/ folder. To build it, I used main.c, Makefile from the linux_server example in the examples/ folder, but I get the following error.

What libraries do I need to install to build and use this project?

**Attachments**

<img width="782" alt="image" src="https://github.com/user-attachments/assets/f6975d1d-6a0d-4a86-baf6-3418a5428720">

**Comment by driftregion** [comment]
Hey @dhje0ng, if you don't mind sharing, what was the issue?
